name: GitHub Deployments
description: GitHub action for working painlessly with deployment statuses.
author: bobheadxi
inputs:
  token:
    description: GitHub token
  step:
    description: One of 'start' and 'finish'
  logs:
    description: URL to logs
  desc:
    description: Description to set in status

runs:
  using: 'node12'
  main: 'lib/main.js'
